### ISSUE TITLE
Installation on integration branch

### ISSUE THREAD

**Issue by nickdunn** [ahwayakchih/gcse#1]
I'm using the latest Symphony integration branch. After installing the extension the option does not show in System. I'm guessing this is because the way to add items to the nav has changed slightly.

I also experiences some CSS formatting issues:
http://nick-dunn.co.uk/assets/files/gcse.png

**Comment by ahwayakchih** [comment]
Thanks. Menu item is now fixed for Symphony 2.0.3.

As for CSS, i get those too. But that also happens on "core" pages, e.g., editing data source, so it may be something wrong with Symphony's admin.css.
