### ISSUE TITLE
HTML entities returning from Google break XSLT transformation

### ISSUE THREAD

**Issue by michael-e** [ahwayakchih/gcse#2]
I explained this bug (including a proposal) in the [Symphony Forum Thread](http://symphony-cms.com/community/discussions/519/2/#position-35)

**Comment by nils-werner** [comment]
Thread on the new Symphony board: http://symphony-cms.com/discuss/thread/519/2/#position-37

**Comment by ahwayakchih** [comment]
Implemented fix suggested by michael-e (http://symphony-cms.com/discuss/thread/519/2/#position-36) and Nickdunn (http://symphony-cms.com/discuss/thread/519/3/#position-43). Thanks everyone :).
