### ISSUE TITLE
Make compatible with Symphony 2.3

### ISSUE THREAD

**Issue by bzerangue** [ahwayakchih/gcse#4]
Is there any plan to update this extension to be compatible with Symphony 2.3? This is a wonderful extension and would love to see it accessible on Symphony 2.3. Since Nick has deprecated his old Symphony search for Elastic Search, there are not a lot options for integration with Symphony in shared environments. 

Would love to see this be upgraded for Symphony 2.3 if possible. 

Thanks so much for your efforts in the Symphony community and sharing such wonderful extensions with us!

Sincerely,
Brian Zerangue
(bzerangue)

**Comment by ahwayakchih** [comment]
Hi Brian,

Thanks a lot for Your work on updating this module!

I'm occupied with other stuff so i could not find time for this :(.

I merged Your changes, thanks again :).

Regards,
ahwayakchih
